FROM jupyter/base-notebook:latest

RUN conda install -c conda-forge cxx-compiler vim 

RUN conda install -c anaconda numpy

RUN conda install -c anaconda swig

RUN conda install -c anaconda make

RUN conda install -c anaconda cmake
